# stocks_etl/config.yaml — REPLACE COMPLETE (MODO DIARIO)
start: "2020-01-01"
end: null
interval: "1d"

# Ajustes de precios y eventos
auto_adjust: false      # (si quieres ver Adj Close poblado, pon false)
actions: true

# Concurrencia y calendario
threads: 1
calendar: "NYSE"

# Salida
output_dir: "data"
csv_compression: null  # null | gzip

# Tickers
symbols:
  - AMZN
  - GOOGL
  - MSFT

# Publicación a Blob
blob_upload:
  enabled: true
  container: "datasets"               # usa env DATASETS_CONTAINER si prefieres
