# ================================
# ETL de Noticias – Config
# ================================

runtime:
  log_level: INFO
  sample_limit: 0           # 0 = sin muestreo

io:
  # El RAW local lo escribe el workflow y aquí solo lo leemos
  input_ndjson: data/news_raw.ndjson
  # Salidas locales (también se suben a Blob)
  output_ndjson: data/news_{{date}}.ndjson
  output_preview_csv: data/news_preview_{{date}}.csv
  heartbeat_file: data/heartbeat.txt

# -------------------------------
# Azure AI Language
# -------------------------------
azure_language:
  endpoint: ${AZURE_LANGUAGE_ENDPOINT}   # defínelo como secret
  key: ${AZURE_LANGUAGE_KEY}             # defínelo como secret
  api_version: "2023-04-01"
  timeout_seconds: 30
  batch_size: 5           # el endpoint limita a 5 docs por petición
  force_language: "en"    # opcional; ayuda cuando el texto es corto/ruidoso

  # Qué tareas queremos pedir a Azure
  tasks:
    language_detection: true
    sentiment_analysis: true
    key_phrase_extraction: true
    entity_recognition: true
    entity_linking: true

# -------------------------------
# Filtrado de fuentes y contenidos
# -------------------------------
filters:
  # Si defines whitelist, SOLO pasan esas fuentes o dominios (case-insensitive).
  # Úsalo para limpiar de raíz entretenimiento/deportes/gossip.
  allowed_sources_whitelist:
    - theverge
    - techcrunch
    - wired
    - ars technica
    - bloomberg
    - reuters
    - wall street journal
    - financial times
    - cnbc
    - the information
    - zdnet
    - verge
    - engadget
    - bbc
    - forbes
    - nytimes
    - pcworld
    - pcmag
    - android police
    - android authority
    - windows central
    - the register
    - tom's hardware
    - notebookcheck
    - slashdot
    - gizmodo
    - xda developers
    - siliconangle
    - venturebeat

  # Bloqueo explícito de fuentes/dominios ruidosos
  source_blacklist:
    - biztoc
    - freerepublic
    - bringatrailer
    - thegatewaypundit
    - pagesix
    - brobible
    - littlethings
    - variety
    - eonline
    - decider
    - buzzfeed
    - the athletic
    - espn
    - the hockey news
    - rolling stone
    - fox news
    - nypost

  # Frases/patrones que queremos excluir en título o URL
  exclude_phrases:
    - (?i)\b(kardashian|mlb|nfl|nba|nhl|wwe|celebrity|gossip|royal family|milkshake|dating|red carpet|reality show)\b
    - (?i)\b(hotel awards|best hotels|travel guide)\b
    - (?i)\b(bringatrailer|porsche|mustang)\b

# Dominios que nunca dejamos pasar (además de source_blacklist)
registry_domains_blacklist:
  - littlethings.com
  - pagesix.com
  - brobible.com
  - thegatewaypundit.com
  - bringatrailer.com
  - eonline.com
  - variety.com
  - espn.com
  - theathletic.com
  - nypost.com
  - foxnews.com

# -------------------------------
# “Commerce filter”
# (para expulsar shopping/afiliados salvo tech de 1a mano)
# -------------------------------
commerce_filter:
  enabled: true
  title_url_terms:
    - (?i)\b(deal|coupon|promo|discount|sale|shopping|buy now|best.*(gadgets|deals|products))\b
  path_terms:
    - (?i)/deals?/
    - (?i)/shopping/
    - (?i)/coupons?/
  allowed_corporate_domains:
    - amazon.com
    - developer.amazon.com
    - blogs.microsoft.com
    - microsoft.com
    - developers.googleblog.com
    - blog.google
    - ai.google
  price_percent_rules:
    price_regex: (?i)\$\s?\d[\d,]*(\.\d{2})?
    percent_regex: (?i)\b\d{1,3}\s?%(\s?off)?\b
    min_price_tokens: 2
    min_percent_tokens: 2

# -------------------------------
# Ticker tagging
# -------------------------------
ticker_tagging:
  enabled: true
  tickers:
    AMZN:
      - (?i)\b(amazon|aws|alexa|prime video|fire tv|kindle|ring|whole foods)\b
    MSFT:
      - (?i)\b(microsoft|azure|copilot|xbox|game pass|windows 11|office 365|m365)\b
    GOOGL:
      - (?i)\b(google|alphabet|youtube|gemini|android|pixel|deepmind|waymo)\b

# -------------------------------
# Azure Blob (sube los CSV/NDJSON)
# -------------------------------
azure_blob:
  enabled: true
  container: datasets
  prefix: news
  # Usamos Connection String del secret: AZURE_STORAGE_CONNECTION_STRING
  connection_string: ${AZURE_STORAGE_CONNECTION_STRING}
  content_types:
    ".csv": text/csv
    ".ndjson": application/x-ndjson
    ".txt": text/plain
