# =========================
# ETL de noticias - Config
# =========================

# --- Ventana temporal ---
date_window:
  days_back: 15          # últimos N días (hoy inclusive)
  tz: "UTC"              # zona para truncar por día (YYYY-MM-DD)

# --- Límite por día ---
daily_limits:
  per_ticker_limit: 3    # máximo por ticker y por día
  include_no_ticker: false
  no_ticker_per_day_limit: 0  # si quieres limitar las “sin ticker”

# --- Fuentes / registro ---
registry:
  # Coloca aquí tus endpoints / providers si los usas.
  # Si tu fetcher ya los trae de otro lado, este bloque puede quedar sin uso.
  providers: []
  # Lista de dominios a permitir (opcional). Si está vacía, no se usa allowlist.
  domains_allowlist: []
  # Blacklist por sufijo (se aplica a subdominios también).
  domains_blacklist:
    - globenewswire.com
    - prnewswire.com
    - businesswire.com
    - tech.slashdot.org       # puedes poner el host exacto o el sufijo base
    - rlsbb.to
    - post.rlsbb.to

# --- Filtros de contenido ---
filters:
  languages_allowlist: ["en", "es", "ja"]  # deja vacío para aceptar todos
  min_title_len: 8
  min_summary_len: 20
  # Blacklist adicional por “source” (campo textual).
  source_blacklist:
    - "GlobeNewswire"
    - "PR Newswire"
  # Palabras/regex para descartar “ofertas/deals” muy comerciales
  commerce:
    min_price_tokens: 1
    min_percent_tokens: 1
    price_regex:
      - "(?i)\\$\\s?\\d+[\\d\\.,]*"
      - "(?i)\\d+\\s?(?:USD|EUR|GBP|dollars?)"
    percent_regex:
      - "(?i)\\d{1,3}%\\s?(?:off|descuento|dto\\.)"

# --- Azure AI Text Analytics ---
azure_language:
  endpoint: "${AZURE_LANGUAGE_ENDPOINT}"  # o pon el endpoint aquí (no recomendado)
  key: "${AZURE_LANGUAGE_KEY}"          # o pon la key aquí (no recomendado)
  api_version: "2023-04-01"
  force_language: "en"                  # e.g., "en" si quieres forzarlo
  timeout_seconds: 30
  tasks:
    language_detection: true
    sentiment_analysis: true
    key_phrase_extraction: true
    entity_recognition: true
    entity_linking: true

# --- Etiquetado de tickers ---
ticker_tagging:
  enabled: true
  # Patrones negativos globales (corta antes de evaluar tickers)
  negative_patterns:
    - "(?i)AMZN\\s*WEB-?DL"
    - "(?i)WEB-?DL\\b"
    - "(?i)RLSBB\\b|rlsbb\\.to"
  tickers:
    AMZN:
      - "(?i)\\bamazon\\b"
      - "(?i)\\baws\\b|\\bamazon web services\\b"
      - "(?i)\\bprime video\\b|\\bkindle\\b|\\bring\\b"
    MSFT:
      - "(?i)\\bmicrosoft\\b|\\bazure\\b|\\bxbox\\b|\\bwindows\\b|\\bmicrosoft 365\\b"
    GOOGL:
      - "(?i)\\bgoogle\\b|\\balphabet\\b|\\byoutube\\b|\\bdeepmind\\b|\\bwaymo\\b"
      # Importante: NO usamos "android" suelto para evitar ruido

# --- Salidas y storage ---
output:
  dir: "data"
  prefix: "news"
  preview_csv: true
  preview_max_rows: 1000

azure_blob:
  enabled: true
  account_url: "https://<TU-CUENTA>.blob.core.windows.net"
  container: "datasets"
  prefix_path: "news"
  sas_token: "${AZ_BLOB_SAS_TOKEN}"  # o usa credenciales por DefaultAzureCredential

# --- Logging ---
logging:
  level: "INFO"
