# news_etl/config.yaml — REPLACE COMPLETE
runtime:
  timezone: UTC
  today_override: ""

window:
  last_n_days: 15

tickers:
  universe:
    AMZN: ["amazon", "aws", "prime video", "kindle", "alexa"]
    MSFT: ["microsoft", "xbox", "azure", "copilot", "windows", "bing"]
    GOOGL: ["google", "alphabet", "youtube", "gemini", "android"]
  restrict_to_universe: true

azure_language:
  enabled: true
  endpoint: "${AZURE_LANGUAGE_ENDPOINT}"
  key: "${AZURE_LANGUAGE_KEY}"
  api_version: "2023-04-01"
  force_language: ""
  tasks:
    language_detection: true
    sentiment_analysis: true
    key_phrase_extraction: true
    entity_recognition: true
    entity_linking: true
  timeout_seconds: 30

limits:
  preview_csv_max_rows: 1000

daily_limits:
  per_ticker_limit: 3
  include_no_ticker: false
  no_ticker_per_day_limit: 0

paths:
  # Acepta archivo, *glob* o directorio. Ejemplos:
  # "data/news_raw.ndjson"  |  "data/raw/news_*.ndjson"  |  "data/raw/"
  raw_ndjson: "data/news_raw.ndjson"
  out_ndjson: "data/news_YYYYMMDD.ndjson"
  out_preview_csv: "data/news_preview_YYYYMMDD.csv"
  heartbeat: "data/heartbeat.txt"

# Publicación a Blob: un solo bloque, sin duplicados
blob_upload:
  enabled: true                 # (cámbialo a false si no quieres subir)
  connection_string: "${AZURE_STORAGE_CONNECTION_STRING}"
  container: "datasets"
  prefix: "news/"              # histórico irá a news/news_YYYYMMDD.* y latest a news/latest/*
