name: ETL Stocks (cron + manual)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      CONTAINER: datasets
      DEST_ROOT: daily
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r stocks_etl/requirements.txt
          pip install pyyaml

      - name: Run ETL (un solo dataset + predicciones)
        run: |
          python -m stocks_etl.stocks_etl --config stocks_etl/config.yaml

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Upload CSVs to Azure Blob
        run: |
          az storage container create \
            --name "$CONTAINER" \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" 1>/dev/null

          DATE=$(date -u +"%Y-%m-%d")
          TIME=$(date -u +"%H%M")

          az storage blob upload-batch \
            --destination "$CONTAINER" \
            --source data \
            --pattern "*.csv*" \
            --destination-path "$DEST_ROOT/$DATE/$TIME" \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
            --overwrite
